Repository jiwonHub/RunningMan, pull requests merged in 2024-06, with the labels that each got.

#27 [FEAT] FBAuthentication OpenId Connection Feat
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/FBStoreUserDataUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/FBStoreUserSignInCase.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/GoogleLoginUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/KakaoLoginUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
Labels: feat

#28 26 featstepsensor stepcounterservice feature
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/MainActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/MainViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/service/PedometerService.kt
  app/src/main/res/drawable/pause_blue.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: feat

#34 33 featmain screen bottomnavigation add
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/MainActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/map/MapFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/SocialFragment.kt
  app/src/main/res/color/navigation_item_color.xml
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/map.png
  app/src/main/res/drawable/person.xml
  app/src/main/res/drawable/social.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_social.xml
  app/src/main/res/menu/navigation_menu.xml
Labels: feat

#36 32 feat userdatastoredinfb
  app/src/main/java/com/cjwjsw/runningman/core/UserLoginFirst.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/AgeScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/GenderScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/HeightScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/WeightScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/onboardingend/OnBoardingEndScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/onboardingend/OnBoardingEndViewModel.kt
Labels: feat

#37 16 featgoogle login logic add
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/cjwjsw/runningman/data/preference/AppPreferenceManager.kt
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/GoogleLoginUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/MainActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/SplashScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginState2.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
  app/src/main/res/values/values.xml
  build.gradle.kts
Labels: bugfix, feat

#44 41 bugbugfixusermanager not stored
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/FBStoreUserSignInCase.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
  build.gradle.kts
Labels: bugfix, bug

#48 42 featgraph activity add
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/presentation/component/LabelUtils.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/component/StatisticsDotLine.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/component/StatisticsProgressBar.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/GraphActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/daily/DailyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/month/MonthlyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/weekly/WeeklyGraphFragment.kt
  app/src/main/res/drawable/arrow_white.xml
  app/src/main/res/drawable/label.xml
  app/src/main/res/drawable/shape_black_circle.xml
  app/src/main/res/layout/activity_graph.xml
  app/src/main/res/layout/fragment_daily_statistics.xml
  app/src/main/res/layout/fragment_month_statistics.xml
  app/src/main/res/layout/fragment_weekly_statistics.xml
Labels: feat, bug
