Repository jiwonHub/RunningMan, pull requests merged in 2024-09, with the labels that each got.

#66 65 featgraph detail activity walk data fetch
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/cjwjsw/runningman/RunningManApplication.kt
  app/src/main/java/com/cjwjsw/runningman/core/FirestoreManager.kt
  app/src/main/java/com/cjwjsw/runningman/core/PreviousWalkData.kt
  app/src/main/java/com/cjwjsw/runningman/core/scheduleDailyDataSync.kt
  app/src/main/java/com/cjwjsw/runningman/core/stepsSettings.kt
  app/src/main/java/com/cjwjsw/runningman/data/data_source/db/WalkDao.kt
  app/src/main/java/com/cjwjsw/runningman/data/repository/WalkRepositoryImpl.kt
  app/src/main/java/com/cjwjsw/runningman/domain/repository/WalkRepository.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/component/LabelUtils.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/GraphActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/GraphViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/daily/DailyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/month/MonthlyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/weekly/WeeklyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/settings/SettingsActivity.kt
  app/src/main/java/com/cjwjsw/runningman/service/worker/DataResetWorker.kt
  app/src/main/java/com/cjwjsw/runningman/service/worker/DataSyncWorker.kt
Labels: feat

#70 65 featgraph detail activity walk data fetch
  app/src/main/java/com/cjwjsw/runningman/data/data_source/db/WalkDatabase.kt
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/component/LabelUtils.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/component/StatisticsProgressBar.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/GraphViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/daily/DailyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/month/MonthlyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/weekly/WeeklyGraphFragment.kt
Labels: feat

#72 69 feat feat profile function
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFeedDetailScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFeedDetailViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileViewAdapter.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileViewModel.kt
Labels: feat, design

#74 [FIX] Fix Feed Profile Image
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/FeedDetailScreen.kt
Labels: fix

#76 75 fix fix like fun
  app/src/main/java/com/cjwjsw/runningman/domain/model/LikeModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/DetailFeedViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/FeedDetailScreen.kt
Labels: fix

#80 [FIX] SettingsViewModel @HiltViewModel 추가
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/settings/SettingsViewModel.kt
Labels: bugfix

#83 82 fixsettingsacticity UI text fix
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/settings/SettingsActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/settings/SettingsViewModel.kt
  app/src/main/res/layout/activity_settings.xml
Labels: bugfix

#85 [FIX] PedometerService 걸음 수 -단위로 찍히는 오류 수정
  app/src/main/java/com/cjwjsw/runningman/service/PedometerService.kt
Labels: bugfix

#86 81 featwater detail activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/RunningManApplication.kt
  app/src/main/java/com/cjwjsw/runningman/core/DataSingleton.kt
  app/src/main/java/com/cjwjsw/runningman/core/Settings.kt
  app/src/main/java/com/cjwjsw/runningman/core/scheduleDailyDataSync.kt
  app/src/main/java/com/cjwjsw/runningman/data/data_source/db/water/WaterDao.kt
  app/src/main/java/com/cjwjsw/runningman/data/data_source/db/water/WaterDatabase.kt
  app/src/main/java/com/cjwjsw/runningman/data/data_source/db/water/WaterEntity.kt
  app/src/main/java/com/cjwjsw/runningman/data/repository/WaterRepositoryImpl.kt
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/domain/repository/WaterRepository.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/component/WaterProgressBar.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/MainViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/daily/DailyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/month/MonthlyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/weekly/WeeklyGraphFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/settings/SettingsActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/WaterActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/WaterViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/watersetting/WaterSettingActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/watersetting/WaterSettingViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/map/MapFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/map/MapViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/receiver/AlarmReceiver.kt
  app/src/main/java/com/cjwjsw/runningman/service/PedometerService.kt
  app/src/main/java/com/cjwjsw/runningman/service/worker/DailyWorker.kt
  app/src/main/java/com/cjwjsw/runningman/service/worker/DataResetWorker.kt
  app/src/main/java/com/cjwjsw/runningman/service/worker/DataSyncWorker.kt
  app/src/main/res/drawable/blue_button.xml
  app/src/main/res/drawable/settings_black.xml
  app/src/main/res/drawable/shape_circle_blue_button.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_water.xml
  app/src/main/res/layout/activity_water_setting.xml
  app/src/main/res/values/strings.xml
Labels: feat

#88 87 featwater activity drinking cancel logic dev
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/domain/model/WaterModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/WaterActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/WaterCaretaker.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/WaterViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/watersetting/WaterSettingActivity.kt
Labels: feat

#90 89 featfixing miscellaneous bugs
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/graph/GraphActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/water/WaterActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/main/weather/WeatherDetailActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/map/MapFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/map/MapViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/service/PedometerService.kt
Labels: bugfix

#92 77 feat feat feed comment delete func
  .idea/.name
  app/.gitignore
  app/build.gradle.kts
  app/libs/activation.jar
  app/libs/additionnal.jar
  app/libs/mail.jar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/domain/model/CommentModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/Comment/Comment2thBottomSheet.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/Comment/CommentAdapter.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/Comment/CommentModalBottomSheet.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/Comment/CommentReportBottomSheet.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/Comment/CommentViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFeedDetailScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFeedDetailViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileViewAdapter.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/DetailFeedViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/FeedDetailScreen.kt
  app/src/main/res/drawable/pepicons_pencil_dots_y.xml
  app/src/main/res/drawable/tabler_trash.xml
  app/src/main/res/layout/activitiy_feed_detail.xml
  app/src/main/res/layout/dialog_comment_bottom_check_report_sheet_modal.xml
  app/src/main/res/layout/dialog_comment_bottom_sheet_2th_modal.xml
  app/src/main/res/layout/item_comment_recycerview.xml
  app/src/main/res/values/values.xml
Labels: feat, design, refactor

#94 93 featui feat work count in profile enhancement UI
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileViewModel.kt
  app/src/main/res/drawable/iconoir_trophy.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: feat, design

#96 95 refactor call firebase func optimization
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/AddFeedActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFeedDetailScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFeedDetailViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/profile/ProfileViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/DetailFeedViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/FeedViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/SocialFragment.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/main/fragment/social/ViewAdapter.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: bugfix, fix
