Repository jiwonHub/RunningMan, pull requests merged in 2024-05, with the labels that each got.

#4 1 featureproject init push splash screen add
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/runningman/presentation/screen/LoginScreen.kt
  app/src/main/java/com/example/runningman/presentation/screen/MainActivity.kt
  app/src/main/java/com/example/runningman/presentation/screen/SplashScreen.kt
  app/src/main/res/drawable/running.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/activity_splash_scene.xml
Labels: feat, refactor

#6 5 featurelogin screen motion login logic
  app/build.gradle.kts
  app/src/androidTest/java/com/cjwjsw/runningman/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/domain/di/Application.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/MainActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/SplashScreen.kt
  app/src/main/res/drawable/google_login.png
  app/src/main/res/drawable/google_login_shape.xml
  app/src/main/res/drawable/kakao_login_medium_wide.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/xml/activity_login_scene.xml
  app/src/test/java/com/cjwjsw/runningman/ExampleUnitTest.kt
  settings.gradle.kts
Labels: feat

#7 5 featurelogin screen motion login logic
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/SplashScreen.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/xml/activity_login_scene.xml
Labels: feat

#9 feature/8 featuredi hilt setting
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/RunningManApplication.kt
  app/src/main/java/com/cjwjsw/runningman/domain/di/Application.kt
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/GoogleLoginUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/KakaoLoginUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/SplashScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  build.gradle.kts
Labels: feat

#15 [FEAT]KakaoLogin Function Implementation
  .idea/.gitignore
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/domain/di/appModule.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/MainActivity.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: feat

#20 19 featureonboarding screen feat 1
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cjwjsw/runningman/core/UserManager.kt
  app/src/main/java/com/cjwjsw/runningman/domain/model/UserModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/SplashScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/AgeScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/GenderScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/HeightScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/WeightScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/onboardingend/OnBoardingEndScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/onboarding/onboardingend/OnBoardingEndViewModel.kt
  app/src/main/res/drawable/blue_background.xml
  app/src/main/res/drawable/gray15_background.xml
  app/src/main/res/drawable/gray26_background.xml
  app/src/main/res/drawable/pink_background.xml
  app/src/main/res/layout/activity_age.xml
  app/src/main/res/layout/activity_gender.xml
  app/src/main/res/layout/activity_height.xml
  app/src/main/res/layout/activity_on_boarding_end.xml
  app/src/main/res/layout/activity_weight.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feat

#22 [REFACTOR] KakaoLogin Logic Refactoring
  app/build.gradle.kts
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/FBStoreUserDataUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/domain/usecase/KakaoLoginUseCase.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginScreen.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginState.kt
  app/src/main/java/com/cjwjsw/runningman/presentation/screen/login/LoginViewModel.kt
Labels: refactor
